const htmlmin = require("html-minifier");

const isProduction = process.env.ELEVENTY_ENV === 'production';

const htmlMinify = function (content) {
	if( (this.page.outputPath && this.page.outputPath.endsWith(".html")) && isProduction ) {
		let minified = htmlmin.minify(content, {
			useShortDoctype: true,
			removeComments: true,
			collapseWhitespace: true,
			collapseBooleanAttributes: true,
			decodeEntities: true,
			includeAutoGeneratedTags: false,
		});
		return minified;
	}
	return content;
}

module.exports = {
	htmlMinify
};
